package hr.dice.filipbionda.githubapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5D5F5F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFFFFF)
val onPrimaryContainerLight = Color(0xFF575859)
val secondaryLight = Color(0xFF5E5E5E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8E6E6)
val onSecondaryContainerLight = Color(0xFF4A4A4A)
val tertiaryLight = Color(0xFF5D5F5F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFFFFF)
val onTertiaryContainerLight = Color(0xFF575859)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCF8F8)
val onBackgroundLight = Color(0xFF1C1B1B)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFC6C6C7)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val searchBackgroundColor = Color(0xFFF1F2F6)
val searchInputHintTextColor = Color(0xFF8C96A5)
val headerTextColor = Color(0xFF858484)
val cardBodyTextColor = Color(0xFF8C96A5)
val repositoryDetailsContentColor = Color(0xFF828888)
